const FORTUNES_WTNV = [
	"Death is only the end if you assume the story is about you.",
	"\x22One day you will die.\x22 Not true! It will likely take several days.",
	"Not everything with a human face is human.",
	"Guns don't kill people. Guns are post-structuralist as heck.",
	"Speak softly and carry a glowing scepter.",
	"At one point, you were the youngest being in the universe. At another point, you will be the next to die.",
	"Fill your heart with bees. If someone breaks your heart, they will have to deal with bees.",
	"Remember: if you see something, say nothing, and drink to forget.",
	"We do not have answers. I am not certain we even have questions.",
	"Some mysteries aren't questions to be answered, but just a kind of opaque fact. A thing which exists to be not known.",
	"Your existence is not impossible. But it's also not very likely.",
	"If at first you don't succeed, look around and find out who is trying to sabotage you with telepathic interference. It is someone you know.",
	"There's nothing under your bed. There's nothing in your closet. Nothing waits in every darkness. Nothing is the most terrifying thing of all.",
	"There is no cause for concern. We're way past that now. If you're not at least feeling mild terror then you haven't been paying attention.",
	"If at first you don't succeed, then you will have alerted them to your presence. It is important that you at first succeed.",
	"There are no dumb questions, only forbidden ones. Your file has been marked for review.",
	"That which does not kill you only wants to watch you suffer a while longer.",
	"Look to the sky. You will not find answers there, but you will certainly see what everyone is screaming about.",
	"Look. Up in the sky. It's a bird. It's a plane. No. It's just the void. Infinite and indifferent. We're so small. So very very small.",
	"Believe in yourself. You are an ancient, absent god, discussed only rarely by literary scholars. So if you don't believe, no one will.",
	"Believe in yourself. Go to a church that worships you. Attend study groups that analyze your words. Argue with others about your existence.",
	"You have nice skin. It really holds in all your blood and organs - no leaking or nothing. You look great.",
	"A partial list of things currently inside you: blood, skull, ghost.",
	"Don't be afraid of spiders! Spiders are your friends! Sorry, that was confusing wording. All your friends are secretly spiders! Better.",
	"If you ever look at the sky, doubting the existence of other worlds, just know that somewhere a creature looks up at its sky, doubting you.",
	"The universe is vast. You are also vast. So is an ant. There are different sizes of infinity.",
	"On this day in history: people related to you whose names you do not know performed actions that were never recorded.",
	"Follow your heart. It's easy to track, because it crawls slowly and leaves a noticeable trail.",
	"You are a special person. In fact, you are one of only a handful to ever inhabit your body.",
	"Let's have a heart to heart. Here's mine, and here's a knife.",
	"Do you have a moment? Do you possess a piece of time? Do you physicalize abstract concepts and keep them to yourself?",
	"Nature will kill you and then make new things from you.",
	"When is a door not a door? That's a great question. We've made some adjustments during the night. Good luck leaving the house.",
	"There is a thin semantic line separating weird and beautiful. And that line is covered in jellyfish.",
	"I like my coffee like I like my nights. Dark, endless, and impossible to sleep through.",
	"The past tense of regret is indecision.",
	"There is no such thing as fiction, only fact written in the wrong parallel universe.",
	"Dream the impossible. Live the improbable. Die from the inevitable.",
	"If you ever find yourself feeling lost, take pride in the accuracy of your feelings.",
	"What has four legs in the morning, two legs at noon, and three legs in the evening? I don't know, but I trapped it in my bedroom. Send help.",
	"Ignorance may not actually be bliss, but it is certainly less work.",
	"The future is what you make of it. Just know that your supplies are limited.",
	"If you love something, set it free. If it doesn't come back, it probably died of sadness because it thought you loved it.",
	"Confused? Unsure what to do? Sounds like you're human. Good luck.",
	"Fear is consciousness plus life. Regret is an attempt to avoid what has already happened. Toast is bread held under direct heat until crisp.",
	"We have nothing to fear except ourselves. We are unholy, awful people. Fear ourselves with silence.",
	"I fear for anyone caught between what they know, and what they don't yet know that they don't know.",
	"May you find love, wherever it's been hidden. May you find who has been hiding it and enact revenge upon them.",
	"Dream big. Dream looming. Dream a force that is so beyond you in scale that you mistake it for the world.",
	"When life seems dangerous and unmanageable, just remember that it is, and that you can't survive forever.",
	"There's a difference between your, you're, and yarn. Yarn isn't even pronounced the same way. It's a completely different word.",
	"Guns don't kill people. It's impossible to be killed by a gun. We are all invincible to bullets and it's a miracle!",
	"Guns don't kill people. Blood loss and organ damage do.",
	"If you say guns kill people one more time, I will shoot you with a gun, and you will (coincidentally) die.",
	"Guns don't kill people. We are all immortal souls living temporarily in shelters of earth and meat.",
	"Guns don't kill people. People kill guns.",
	"A list of things that kill people: 1) conceivably anything. 2) not guns.",
	"First comes love. Then comes marriage. Then comes nitrate. Then olives. We're not letting you go until you've alphabetized all these nouns.",
	"And now a brief public service announcement. Alligators: can they kill your children? Yes.",
	"The only thing we have to fear is a tarantula hiding in our glove.",
	"Hey, why not take a run? Get that body moving. Take in the fresh air while running. Running away. Fleeing. They're almost upon you.",
	"Is your refridgerator running? I mean dying. I mean the sun. Is the sun dying? Let me start over...",
	"April fools. May idiots. June lunatics. July gibbering husks. By August, there is nothing left of us.",
	"Is it larger than a breadbox? YES. Is it crawling on me right now? YES. Is it a kind of larva? KIND OF. Am I screaming? YES. Loudly? YES.",
	"Ask your doctor if earth's gravity is right for you.",
	"Ask your doctor if a chest full of wet leaves and caterpillars is right for you.",
	"I will tell you an important secret. I will also tell you volumes of worthless nonsense. You will never know which is which.",
	"Getting there is half the fun. The other half happens years later, after you've fully recovered from the physical/mental horror.",
	"Make like a banana and attract large spiders.",
	"Bury the hatchet. Hide the axe. Ignore the razor. Deny the table saw. Pretend the knife isn't real.",
	"The shortest distance between two points is this cave. It's a really convenient cave. It changes your DNA a bit, but what a time saver.",
	"There's a fine line between sanity and horrifying hellscape. That line was drawn with chalk in a small circle around you. Stay still okay.",
	"Ask your doctor if you're covered in spiders.",
	"Ask your doctor a question only she would know, the knife clutched behind your back, your arm tensed and ready.",
	"Ask your doctor why he is screaming and backing away from you.",
	"All living things will someday die. All dead things will someday glow red and emit a beautiful song. No one will be alive to hear it.",
	"Ask your doctor a series of coded questions before offering her the briefcase full of stolen documents.",
	"Where there's smoke, there's that weird bird that bleeds smoke. I think he's injured.",
	"Ask your doctor where your skin is.",
	"Looking for a job? We can't help you. Looking for a quivering mute creature of indeterminate size and origin, hiding in a deep pit? Great news!",
	"Ask your doctor if he wants to see a dead body.",
	"You are what you eat. You are a spider 8 times a year.",
	"A word of warning: look. A clause of warning: look out. A phrase of warning: look out for that falling rock. A note of regret: oops. Oh well.",
	"If you love someone, let them go. If they come back, that curse you learned worked.",
	"If you love something, let it go. If it comes back, you're doomed, because it's very hungry.",
	"It takes heart. It takes guts. It also takes cash. It just needs payment asap.",
	"Be the crippling fear you want to see in the world.",
	"It's darkest before the dawn. Usually not this dark, though. Wow, this is like pitch black. Wasn't dawn supposed to be two hours ago?",
	"Ask your doctor if you are a tree, if we are all trees, if everything is a single being of shared roots and majestic limbs.",
	"Ask your doctor to get away. Ask him to stand back and stop looking directly at you. Ask your doctor if he believes in the devil. Ask him.",
	"Ask your doctor a seemingly innocent question. Tap the side of your nose. Say \x22perhaps I have said too much.\x22 Say it again.",
	"Ask your doctor just how many of you there are. Ask her what she told the others. What did she tell the others?",
	"Wow, the continuous nuclear explosion in the sky is really nice today. Hardly any floating water in the way.",
	"Ask your doctor if you're already dead. Ask your doctor if she can even see you. Ask your doctor this while waving your arms. Ask louder.",
	"Ask your doctor if you can go. Tell your doctor that you won't alert anyone about the Plan. Try to sneak away when your doctor isn't looking.",
	"Whatever's in your oven smells good. Oh, sorry, it smells WELL. It also has excellent vision and three rows of teeth. Chain your oven shut.",
	"\x22Nobody knows what that thing is, or why it's here,\x22 says the scientist, pointing to everything.",
	"Ask your doctor why there are no windows, no doors. Ask your doctor why you cannot see, hear her.",
	"Summer tips to beat the heat: deny the heat. What heat?",
	"Summer tips to beat the heat: spread rumors about the heat. Report imagined suspicions about the heat to the government.",
	"Ask your doctor why there are claw marks on the wall. Ask your doctor to stop growling. Ask your doctor to stop climbing and smelling you.",
	"The best way to stay in shape is a skeleton. Skin also helps. Without those you wouldn't have any shape at all.",
	"Ask your doctor a question. Receive an answer. Shiver. Think about the answer. Shiver. Think about the answer. Think about it. Shiver.",
	"You can tell a lot about a person by using spy cameras and a team of agents to investigate every private facet of their life.",
	"Looking for a simple solution to all life's problems? We are proud to present obstinate denial. Accept no substitute. Accept nothing.",
	"Ask your doctor if anyone will hear his screams. Ask again in a firm whisper. Ask again with just your crooked smile.",
	"Ask your doctor if cats are supposed to do that. Tell your doctor that you don't think they are. \x22They aren't right?\x22 whisper to your doctor.",
	"One way to test if someone is actually dead is to think about when that person was born. Was it 400 years ago? Probably dead.",
	"The only bad question is the one not asked. And don't you dare ask it. It's a terrible question.",
	"Shoot for the moon. Even if you miss, you will have plenty of time to regret your hubris as you drift for infinity through the void.",
	"Follow your heart. It's in a cooler in the back of that van up ahead. Step on it. They're getting away.",
	"\x22It's always darkest before the dawn,\x22 we are often reassured by people who are totally wrong about how the sun works.",
	"When a door closes, a window opens. This contractor did a terrible job.\n",
];
